print("CIRCLE")
r=int(input("Enter the radius "))
print("Area of circle is ",3.14*r*r)
print("Perimeter of circle is ",2*3.14*r)
print("\nTRIANGLE")
a=int(input("Enter side 1 "))
b=int(input("Enter side 2 "))
c=int(input("Enter side 3 "))
base=int(input("Enter base "))
height=int(input("Enter height "))
print("Area of triangle is ",0.5*base*height)
print("Perimeter of triangle is ",a+b+c)
print("\nSQUARE")
p=int(input("Enter the length of side "))
print("Area of Square is ",p*p)
print("Perimeter of Square is ",4*p)
print("\nRECTANGLE")
l=int(input("Enter the length  "))
w=int(input("Enter the width  "))
print("Area of rectangle is ",l*w)
print("Perimeter of rectangle is ",2*(l+w))
print("\nPARALLELOGRAM")
s=int(input("Enter the side "))
k=int(input("Enter the base "))
v=int(input("Enter the vertical height "))
print("Area of Parallelogram  is ",k*v)
print("Perimeter of Parallelogram  is ",2*(s+k))


